### ISSUE TITLE
Matplotlib.pyplot.fill_between function error in openEO_NDVItimeseriesAnalysis example 

### ISSUE THREAD

**Issue by Mmoncadaisla** [c-scale-community/c-scale-tutorial-openeo#1]
### Context

When running the `openEO_NDVItimeseriesAnalysis` notebook, step "2.8  Visualize the result" the following error is prompted:

```python
timeser = pd.read_csv("timeseries.csv")
timeser.index = pd.to_datetime(timeser.date)
timeser.columns = ["date","feature_index","Mean NDVI", "SD"]
timeser = timeser.sort_index()

plt.plot(timeser["Mean NDVI"],"o-")
plt.fill_between(timeser.index,
                 timeser["Mean NDVI"] - timeser["SD"], 
                 timeser["Mean NDVI"] + timeser["SD"],
                 color='gray', alpha=0.2)
plt.ylim(0,1)
plt.xticks(rotation=45)
plt.title("Potato")
plt.show()
``` 

Error traceback:

```python
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

### Environment settings

- OS: MacOS BigSur
- Python version: `3.8`
- Environment manager: `conda`
- Relevant package versions:

```bash
pip freeze | grep -iE "numpy|shapely|geopandas|matplotlib"
```

 ```
geopandas==0.9.0
matplotlib==3.6.2
matplotlib-inline @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_9ddl71oqte/croots/recipe/matplotlib-inline_1662014471815/work
numpy==1.24.0
numpydoc @ file:///tmp/build/80754af9/numpydoc_1605117425582/work
shapely==2.0.0
```

### Suggestions

Per [this thread](https://stackoverflow.com/questions/40809503/python-numpy-typeerror-ufunc-isfinite-not-supported-for-the-input-types) it seems to be due to the input provided to the function, we were able to overcome this error through the following adaptation:

```python
import numpy as np # Imported in imports section
timeser = pd.read_csv("timeseries.csv")
timeser.index = pd.to_datetime(timeser.date)
timeser.columns = ["date", "feature_index", "Mean NDVI", "SD"]
timeser = timeser.sort_index()

plt.plot(timeser["Mean NDVI"], "o-")
plt.fill_between(timeser.index,
                 np.array(timeser["Mean NDVI"] - timeser["SD"], dtype=float),
                 np.array(timeser["Mean NDVI"] + timeser["SD"], dtype=float),
                 color='gray', alpha=0.2)
plt.ylim(0, 1)
plt.xticks(rotation=45)
plt.title("Potato")
plt.show()
```

Result:

![image](https://user-images.githubusercontent.com/48254102/209466512-fc5e1fc1-6eb5-4d3d-971e-1bcab1e7575a.png)

**Comment by Mmoncadaisla** [comment]
@bschumac first, thanks a lot for putting these examples (and video tutorial) together, it looks great! 

This is not urgent at all, but just in case this is helpful for any other user that could encounter the same bump on the road. We couldn't find a template to submit issues here, let us know if there is any useful information that we might have missed or if there's anything we could do to help!

Thanks so much! 🙇🏼‍♂️

**Comment by bschumac** [comment]
@Mmoncadaisla which account did you use to run the notebook? I had provided you a testing account which you can use in the JupyterLab env on openeo.cloud. Did you check there as well?

**Comment by Mmoncadaisla** [comment]
Hi @bschumac sorry for the delay in our response. 

We had used an early adopter account for this, via a local Jupyter Notebook as we were not aware that there was an available JupyterLab environment on `openeo.cloud`, this is probably related as the error seems to correspond with package dependency. 

I think we can close this one, thanks a lot for your assistance!
